### ISSUE TITLE
Resizing the simulator window manually occasionally causes it to lock up.

### ISSUE THREAD

**Issue by jdaymude** [SOPSLab/AmoebotSim#11] opened 2019-12-13 22:09 UTC
**Description**
Resizing the simulator window manually occasionally causes it to lock up, unable to be resized. This needs to be investigated further and fixed if possible. (Note: it doesn't appear to happen for the 3D simulator).

**To Reproduce**

1. Run AmoebotSim.
2. Hover over the edges of the window for the simulator until you get the double-headed arrows for your cursor, giving you the ability to resize the window.
3. Resize the window multiple times in succession until you see black flashes.
4. The window should now be locked, unable to be resized.

**Expected Behavior**
The simulator window should be resizable regardless of past interactions.

**Platform**
Observed on Windows, but could also be happening on macOS.

**Comment by josephbriones** [comment] 2020-02-25 18:32
I was unable to reproduce this issue on Mac.

**Comment by jdaymude** [comment] 2020-02-25 20:28
I attempted to reproduce the issue on Windows 10 using Qt 5.14.1 and Qt Creator 4.11.1. I was able to reproduce steps 1-3 (up until the black flashes), but it didn't lock up. @ryanyiu can you check this on your machine as well?

On macOS 10.15.3 with the same Qt/Qt Creator versions, it not only didn't lock up but also didn't have any black flashes.

As long as Ryan doesn't see the bug on his machine, I think we can close this issue.

**Comment by ryanyiu** [comment] 2020-02-25 23:29
I've been unable to reproduce this issue now, so I'll close the issue.

**Closed as completed by ryanyiu** 2020-02-25 23:29 UTC
Labels: bug, diff-medium, windows
